import StickyLayout from './StickyLayout';
import FadeIn from './FadeIn';

const assets = [
    { type: 'video', src: '/ads/video1.mp4', label: 'LUXURY CAR' },
    { type: 'image', src: '/ads/image1.png', label: 'REAL ESTATE' },
    { type: 'video', src: '/ads/video2.mp4', label: 'FASHION FILM' },
    { type: 'image', src: '/ads/image2.png', label: 'STREETWEAR' },
    { type: 'video', src: '/ads/video3.mp4', label: 'AI MARKETING' },
    { type: 'image', src: '/ads/image3.png', label: 'FITNESS' },
    { type: 'video', src: '/ads/video4.mp4', label: 'TECH PROMO' },
    { type: 'image', src: '/ads/image4.png', label: 'SAAS DASHBOARD' },
];

export default function AIGallery() {
    return (
        <StickyLayout
            id="ai"
            title="AI Ads Gallery"
            subtitle="High-converting creative assets generated by AI. From video to static, we build it all."
        >
            <div className="columns-1 md:columns-2 gap-4 space-y-4">
                {assets.map((asset, idx) => (
                    <FadeIn key={idx} delay={idx * 0.05}>
                        <div className="rounded-xl overflow-hidden break-inside-avoid relative group bg-white/5 border border-white/10">
                            {asset.type === 'video' ? (
                                <video
                                    src={asset.src}
                                    autoPlay
                                    muted
                                    loop
                                    playsInline
                                    className="w-full h-auto object-cover"
                                />
                            ) : (
                                <img
                                    src={asset.src}
                                    alt={asset.label}
                                    className="w-full h-auto object-cover"
                                />
                            )}
                            <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                                <span className="text-white font-mono text-sm tracking-widest border border-white/30 px-3 py-1 rounded-full backdrop-blur-sm">
                                    {asset.label}
                                </span>
                            </div>
                        </div>
                    </FadeIn>
                ))}
            </div>
        </StickyLayout>
    );
}
